### ISSUE TITLE
Assorted issues before first run

### ISSUE THREAD

**Issue by arefindk** [manashmndl/NewsCrawler#14]
## 1. Update the description in readme.md after you verify them:
You might need to update the nltk corpuses to properly run the newspaper library
`python -m nltk.downloader all`

## 2. Update the description in readme.md after you verify it:
To encounter the lxml error while installing newspaper using pip in ubuntu:
`sudo apt-get install python-dev libxml2-dev libxslt1-dev zlib1g-dev`
http://stackoverflow.com/questions/5178416/pip-install-lxml-error

## 3. Update the description in readme.md after you verify it:

To encounter jpeg is required error while installing  indicoio

```
sudo apt-get install libtiff5-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python-tk
```

## 4. Update the description in readme.md after you verify it:
You need to update the default nltk 2.x to 3.x so that nltk.tag works
```
pip install -U nltk
```

## 5. Update the description in readme.md after you verify it:
You forgot to add this in the requirements
```
pip install wget
```

## 6. Update the description in readme.md after you verify it:
make sure adding a single path name would suffice

here is another place Newcrawler/newscralwer/credentials where you need the pathname

## 7. Update the description in readme.md after you verify it:
Adding the path and api key in the root folder does not make any difference, it seems that the actual configurations files are. the files in ` NewsCrawler/NewsCrawler/credentials_and_configs` directory 

There is problem with indentation, in all the crawler files, it was resolved when I used sublime to convert all indentation to tabs then it is resolved

## 8. You forgot to  `import re`,

but used re somewhere in the middle of the codes in the dailystar and prothomalo file, but it was imported in the dtribune crawler.

## 13. what does shoulder keyword stand for inside the data inserted in elasticsearch?

**Comment by manashmndl** [comment]
# NLTK
## Downloading Language Models and Corpus
```
python -m nltk.downloader all
```
or,
```python
>>> import nltk
>>> nltk.download()
```
# Downloading Image

I am saving the downloaded files at
```
NewsCrawler /

```
## Updating NLTK
```
pip install -U nltk
```
To use StanfordNERTagger nltk 3.x.x version is required

**Comment by arefindk** [comment]
### Python string to date conversion example:
```python
from dateutil import parser  
dt = parser.parse("Aug 28 1999 12:00AM")  
```
Now, you will insert this date object to the database, not the previous string object.

**Comment by manashmndl** [comment]
# `Shoulder` keyword:

There is a special section/keyword used in `dhakatribune` website which is named `shoulder`

![shoulder](http://i.imgur.com/sy4cryG.png)

From the following figure, it can be seen that the `INSIGHT` keyword is the `shoulder` of that article.

**Comment by arefindk** [comment]
I think most of the issues are resolved by @manashmndl
